function m(a,b){return a[b]|a[b+1]<<8|a[b+2]<<16|a[b+3]<<24}function n(a,b,c){for(var d=[],f=[],e=0,h=0;b<c;){var g=a[b];++b;if(0==g)0<f.length&&(d.push(String.fromCharCode.apply(null,f)),f=[]),h=e=0;else if(0==h)if(128>g)f.push(g);else if(192>g)break;else if(224>g)e=g&31,h=1;else if(240>g)e=g&15,h=2;else if(248>g)e=g&7,h=3;else break;else if(128>g||224<=g)break;else e=e<<6|g&63,0==--h&&(65536>e?f.push(e):(e-=65536,f.push(55296+(e&1023),56320+(e>>10&1023))))}return d}
function p(a){if(a&&3<a.length){var b=a[2],c=a[4]||"";this.d=a[3];this.i="0"==b?"":b;this.l="."==c?"":c;this.m=null}}p.prototype.k=function(a,b,c){if(a.length<=this.d.length)return!0;a=this.o(a);if(0==a.length||0!=this.l.length&&(this.m||(this.m=RegExp(this.n())),!this.m.test(a)))return!0;c.c=q(c,a,b);return!c.c};p.prototype.o=function(){return""};p.prototype.n=function(){return""};function r(a){p.call(this,a)}r.prototype=Object.create(p.prototype);
r.prototype.o=function(a){var b=this.d.length;if(a.substring(0,b)!=this.d)return"";a=a.substring(b);0!=this.i.length&&(a=this.i+a);return a};r.prototype.n=function(){return"^"+this.l};function s(a){p.call(this,a)}s.prototype=Object.create(p.prototype);s.prototype.o=function(a){var b=a.length-this.d.length;if(a.substring(b)!=this.d)return"";a=a.substring(0,b);0!=this.i.length&&(a+=this.i);return a};s.prototype.n=function(){return this.l+"$"};
function t(a){var b=a[1],c=a[3];this.I="Y"==a[2];this.B=b;this.H=c?~~c:0;this.h=[]}t.prototype.f=function(a,b){for(var c=this.h.length;0<=--c;)if(!this.h[c].k(a,this.B,b))return!1;return!0};function u(a,b){this.t=a;this.C=b}u.prototype.k=function(a,b){for(var c=this.t.length,d=0;0<=(d=a.indexOf(this.t,d));){var f=0==d?"":a.substring(0,d),f=f+this.C,f=f+a.substring(d+c);if(!v(b,f))return!0;d+=c}return!1};
function w(a,b){var c=m(a,8);if(!(0>c||c>=b)){var d=m(a,c),f=m(a,c+4),e=m(a,c+8),c=m(a,c+12);this.J=a[4]|a[5]<<8;this.K=a[6]|a[7]<<8;this.q=m(a,12);for(var d=n(a,d,f),h=[""],g=1;g<d.length;++g){var k=d[g].split(" ");if(2!=k.length||"AF"!=k[0])break;h.push(k[1])}this.w=h;f=n(a,f,e);d=[];h={};for(g=0;g<f.length;++g){var l=f[g].split(" ");if(4>l.length)break;var H=l[0],k=l[1];h[k]?"SFX"==H?h[k].h.push(new s(l)):"PFX"==H&&h[k].h.push(new r(l)):(l=new t(l),d.push(l),h[k]=l)}this.p=d;e=n(a,e,c);c=[];f=
e.length&-2;for(d=0;d<f;d+=2)c.push(new u(e[d],e[d+1]));this.u=c}}w.prototype.f=function(a,b){for(var c=this.p.length,d=0;d<c;++d)if(!this.p[d].f(a,b))return!1;return!0};
function x(a){for(var b=a.length,c=[],d=0,f=0;f<b;++f){var e=a.charCodeAt(f);if(0!=d){if(56320<=e&&57344>e)e=65536|d-55296<<10|e-56320;else break;d=0}if(128>e)c.push(e);else if(55296<=e&&56320>e)d=e;else{var h=128|e&63,e=e>>6;if(32>e)c.push(192|e,h);else{var g=128|e&63,e=e>>6;if(16>e)c.push(224|e,g,h);else{var k=128|e&63,e=e>>6;if(8>e)c.push(240|e,k,g,h);else break}}}}this.a=c;this.s=-1;this.G=this.a.length-1}function y(a){return a.s>=a.G?0:a.a[++a.s]}function z(a,b){this.a=a;this.e=b}
z.prototype.g=function(){return-1};z.prototype.r=function(){return[]};function A(a,b){z.call(this,a,b);this.j=[]}A.prototype=Object.create(z.prototype);A.prototype.g=function(a){var b=this.e,c=this.a[b],d=(c<<8|this.a[++b])&8191;if(c&64)for(var f=0;0!=(f=this.a[++b]);)if(y(a)!=f)return-1;if(0!=y(a))return-1;8191!=d&&this.j.push(d);if(c&32){do d=this.a[++b],d|=this.a[++b]<<8,this.j.push(d);while(65535!=d)}return 0};A.prototype.r=function(){return this.j};function B(a,b){z.call(this,a,b)}
B.prototype=Object.create(z.prototype);B.prototype.g=function(a){var b=this.e,c=this.a[b],d=c&16?2:1,c=c&15;a=y(a);for(var f=0;f<c;++f){if(a==this.a[++b])return a=this.a[++b],1==d?b=2*c+a:(a|=this.a[++b]<<8,b=3*c+a),this.e+1+b;b+=d}return-1};function C(a,b){z.call(this,a,b)}C.prototype=Object.create(z.prototype);
C.prototype.g=function(a){var b=this.e,c=this.a[b],d=this.a[++b],f=this.a[++b];a=y(a);var e=c&1;if(0==a){if(0==e)return-1}else{a-=d;if(0>a|a>=f)return-1;a+=e}c&2?(a=b+4*a,b=m(this.a,++a)):(a=b+2*a,b=this.a,c=++a,b=b[c]|b[c+1]<<8,b+=this.e);return b};function D(a){this.a=a}D.prototype.createNode=function(a){var b=this.a[a];return 192==(b&252)?new C(this.a,a):224==(b&224)?new B(this.a,a):0==(b&128)?new A(this.a,a):null};
function E(a,b){this.a=a;this.D=b;this.b=null;this.A=new D(a);this.c=!1;this.v=[]}function q(a,b,c){b=new x(b);var d=a.b.q;do{var f=a.A.createNode(d);if(!f)break;d=f.g(b);if(0==d){if(0==c.length)a=!0;else a:{b=f.r();d=b.length;for(f=0;f<d;++f)if(0<=a.b.w[b[f]].indexOf(c)){a=!0;break a}a=!1}return a}}while(0<d);return!1}function v(a,b){a:{if(!q(a,b,"")&&(a.c=!1,a.b.f(b,a),!a.c))break a;a.v.push(b)}return!0}
E.prototype.F=function(a,b){if(!this.b&&(this.b=new w(this.a,this.D),!this.b.q)||q(this,a,""))return!0;this.c=!1;this.b.f(a,this);var c=this.c;if(!c&&b){this.v=b;var d=this.b;if(v(this,a.toUpperCase()))for(var f=d.u.length,e=0;e<f&&!d.u[e].k(a,this);++e);}return c};for(var F={spell:E.prototype.F},G=["org","jsspell","SpellChecker"],I=self,J=G.length-1,K=0;K<J;++K)var L=G[K],I=I[L]?I[L]:I[L]={};I[G[J]]=E;for(var M in F)E.prototype[M]=F[M];
