function k(a,b){return a[b]|a[b+1]<<8|a[b+2]<<16|a[b+3]<<24}function l(a,b,d){for(var e=[],f=[],c=0,g=0;b<d;){var h=a[++b];if(0==h)0<f.length&&(e.push(String.fromCharCode.apply(null,f)),f=[]),g=c=0;else if(0==g)if(128>h)f.push(h);else if(192>h)break;else if(224>h)c=h&31,g=1;else if(240>h)c=h&15,g=2;else if(248>h)c=h&7,g=3;else break;else if(128>h||224<=h)break;else c=c<<6|h&63,0==--g&&(65536>c?f.push(c):(c-=65536,f.push(55296+(c&1023),56320+(c>>10&1023))))}return e}
function m(a){if(a&&3<a.length){var b=a[2],d=a[4]||"";this.e=a[3];this.j="0"==b?"":b;this.l="."==d?"":d;this.m=null}}m.prototype.o=function(){return""};m.prototype.n=function(){return""};function p(a){m.call(this,a)}p.prototype=new m;p.prototype.o=function(a){var b=this.e.length;if(a.substring(0,b)!=this.e)return"";a=a.substring(b);0!=this.j.length&&(a=this.j+a);return a};p.prototype.n=function(){return"^"+this.l};function q(a){m.call(this,a)}q.prototype=new m;
q.prototype.o=function(a){var b=a.length-this.e.length;if(a.substring(b)!=this.e)return"";a=a.substring(0,b);0!=this.j.length&&(a+=this.j);return a};q.prototype.n=function(){return this.l+"$"};function r(a){var b=a[1],d=a[3];this.D="Y"==a[2];this.w=b;this.C=d?~~d:0;this.b=[]}r.prototype.addRule=function(a){this.b.push(a)};
r.prototype.f=function(a,b){for(var d=this.b.length;0<=--d;){var e;a:{var f=this.b[d];e=this.w;var c=b;if(a.length<=f.e.length)e=!0;else{var g=f.o(a);if(0==g.length)e=!0;else{if(0!=f.l.length&&(f.m||(f.m=RegExp(f.n())),!f.m.test(g))){e=!0;break a}f=c;f.d=s(f,g,e);e=!f.d}}}if(!e)return!1}return!0};function t(a,b){this.data=a;this.size=b;this.F=a[4]|a[5]<<8;this.G=a[6]|a[7]<<8;this.u=k(a,12);this.i=0;this.r=[];this.h={};this.b=[];this.p=[]}
function u(a){if(0!=a.i)return 0<a.i;a.i=-1;var b=k(a.data,8);if(0>b||b>=a.size)return!1;for(var d=k(a.data,b+4)-1,e=k(a.data,b+8)-1,f=k(a.data,b+12)-1,c=l(a.data,k(a.data,b)-1,d),b=1;b<c.length;++b){var g=c[b].split(" ");if(2!=g.length||"AF"!=g[0])return!1;a.r.push(g[1])}d=l(a.data,d,e);for(b=0;b<d.length;++b){g=d[b].split(" ");if(4>g.length)return!1;var h=g[0],c=g[1];a.h[c]?"SFX"==h?a.h[c].addRule(new q(g)):"PFX"==h&&a.h[c].addRule(new p(g)):(g=new r(g),a.b.push(g),a.h[c]=g)}a.p=l(a.data,e,f);a.i=
1;return!0}t.prototype.f=function(a,b){for(var d=this.b.length,e=0;e<d;++e)if(!this.b[e].f(a,b))return!1;return!0};
function v(a){for(var b=a.length,d=[],e=0,f=0;f<b;++f){var c=a.charCodeAt(f);if(0!=e){if(56320<=c&&57344>c)c=65536|e-55296<<10|c-56320;else break;e=0}if(128>c)d.push(c);else if(55296<=c&&56320>c)e=c;else{var g=128|c&63,c=c>>6;if(32>c)d.push(192|c,g);else{var h=128|c&63,c=c>>6;if(16>c)d.push(224|c,h,g);else{var n=128|c&63,c=c>>6;if(8>c)d.push(240|c,n,h,g);else break}}}}this.a=d;this.s=-1;this.B=this.a.length-1}function w(a){return a.s>=a.B?0:a.a[++a.s]}function x(a,b){this.data=a;this.offset=b}
x.prototype.g=function(){return-1};x.prototype.q=function(){return[]};function y(a,b){x.call(this,a,b);this.k=[]}y.prototype=new x(null,0);y.prototype.g=function(a){var b=this.offset,d=this.data[b],e=(d<<8|this.data[++b])&8191;if(d&64)for(var f=0;0!=(f=this.data[++b]);)if(w(a)!=f)return-1;if(0!=w(a))return-1;8191!=e&&this.k.push(e);if(d&32){do e=this.data[++b],e|=this.data[++b]<<8,this.k.push(e);while(65535!=e)}return 0};y.prototype.q=function(){return this.k};function z(a,b){x.call(this,a,b)}
z.prototype=new x(null,0);z.prototype.g=function(a){var b=this.offset,d=this.data[b],e=d&16?2:1,d=d&15;a=w(a);for(var f=0;f<d;++f){if(a==this.data[++b])return a=this.data[++b],1==e?b=2*d+a:(a|=this.data[++b]<<8,b=3*d+a),this.offset+1+b;b+=e}return-1};function A(a,b){x.call(this,a,b)}A.prototype=new x(null,0);
A.prototype.g=function(a){var b=this.offset,d=this.data[b],e=this.data[++b],f=this.data[++b];a=w(a);var c=d&1;if(0==a){if(0==c)return-1}else{a-=e;if(0>a|a>=f)return-1;a+=c}d&2?(a=b+4*a,b=k(this.data,++a)):(a=b+2*a,b=this.data,d=++a,b=b[d]|b[d+1]<<8,b+=this.offset);return b};function B(a){this.a=a}B.prototype.createNode=function(a){var b=this.a[a];return 192==(b&252)?new A(this.a,a):224==(b&224)?new z(this.a,a):0==(b&128)?new y(this.a,a):null};
function C(a,b){this.c=new t(a,b);this.v=new B(a);this.d=!1;this.t=[]}function s(a,b,d){b=new v(b);var e=a.c.u;do{var f=a.v.createNode(e);if(!f)break;e=f.g(b);if(0==e){if(0==d.length)a=!0;else a:{b=f.q();e=b.length;for(f=0;f<e;++f)if(0<=a.c.r[b[f]].indexOf(d)){a=!0;break a}a=!1}return a}}while(0<e);return!1}function D(a,b){a:{if(!s(a,b,"")&&(a.d=!1,a.c.f(b,a),!a.d))break a;a.t.push(b)}return!0}
C.prototype.A=function(a,b){if(!u(this.c)||s(this,a,""))return!0;this.d=!1;this.c.f(a,this);var d=this.d;if(!d&&b){this.t=b;a:{var e=this.c;if(D(this,a.toUpperCase()))for(var f=e.p.length&-2,c=0;c<f;c+=2)for(var g=e.p[c],h=g.length,n=0;0<=(n=a.indexOf(g,n));){if(!D(this,a))break a;n+=h}}}return d};for(var E={spell:C.prototype.A},F=["org","jsspell","SpellChecker"],G=self,H=F.length-1,I=0;I<H;++I)var J=F[I],G=G[J]?G[J]:G[J]={};G[F[H]]=C;for(var K in E)C.prototype[K]=E[K];
