function m(a,b){return a[b]|a[b+1]<<8|a[b+2]<<16|a[b+3]<<24}function n(a,b,c){for(var d=[],f=[],e=0,h=0;b<c;){var g=a[b];++b;if(0==g)0<f.length&&(d.push(String.fromCharCode.apply(null,f)),f=[]),h=e=0;else if(0==h)if(128>g)f.push(g);else if(192>g)break;else if(224>g)e=g&31,h=1;else if(240>g)e=g&15,h=2;else if(248>g)e=g&7,h=3;else break;else if(128>g||224<=g)break;else e=e<<6|g&63,0==--h&&(65536>e?f.push(e):(e-=65536,f.push(55296+(e&1023),56320+(e>>10&1023))))}return d}
function p(a){var b=a[2],c=a[4]||"";this.e=a[3];this.i="0"==b?"":b;this.k="."==c?"":c;this.l=null}p.prototype.c=function(a,b,c){if(a.length<=this.e.length)return!0;a=this.n(a);if(0==a.length||0!=this.k.length&&(this.l||(this.l=RegExp(this.m())),!this.l.test(a)))return!0;c.d=q(c,a,b);return!c.d};p.prototype.n=function(){return""};p.prototype.m=function(){return""};function r(a){p.call(this,a)}r.prototype=Object.create(p.prototype);
r.prototype.n=function(a){var b=this.e.length;if(a.substring(0,b)!=this.e)return"";a=a.substring(b);0!=this.i.length&&(a=this.i+a);return a};r.prototype.m=function(){return"^"+this.k};function s(a){p.call(this,a)}s.prototype=Object.create(p.prototype);s.prototype.n=function(a){var b=a.length-this.e.length;if(a.substring(b)!=this.e)return"";a=a.substring(0,b);0!=this.i.length&&(a+=this.i);return a};s.prototype.m=function(){return this.k+"$"};
function t(a){var b=a[1],c=a[3];this.H="Y"==a[2];this.A=b;this.G=c?~~c:0;this.h=[]}t.prototype.c=function(a,b){for(var c=this.h.length;0<=--c;)if(!this.h[c].c(a,this.A,b))return!1;return!0};function u(){}u.prototype.c=function(a,b){v(b,a.toUpperCase());return!1};function w(a,b){this.s=a;this.B=b}w.prototype.c=function(a,b){for(var c=this.s.length,d=0;0<=(d=a.indexOf(this.s,d));){var f=0==d?"":a.substring(0,d),f=f+this.B,f=f+a.substring(d+c);v(b,f);d+=c}return!1};
function x(a,b){var c=m(a,8);if(!(0>c||c>=b)){var d=m(a,c),f=m(a,c+4),e=m(a,c+8),c=m(a,c+12);this.I=a[4]|a[5]<<8;this.J=a[6]|a[7]<<8;this.p=m(a,12);for(var d=n(a,d,f),h=[""],g=1;g<d.length;++g){var k=d[g].split(" ");if(2!=k.length||"AF"!=k[0])break;h.push(k[1])}this.v=h;f=n(a,f,e);d=[];h={};for(g=0;g<f.length;++g){var l=f[g].split(" ");if(4>l.length)break;var H=l[0],k=l[1];h[k]?"SFX"==H?h[k].h.push(new s(l)):"PFX"==H&&h[k].h.push(new r(l)):(l=new t(l),d.push(l),h[k]=l)}this.o=d;f=[];f.push(new u);
e=n(a,e,c);c=e.length&-2;for(d=0;d<c;d+=2)f.push(new w(e[d],e[d+1]));this.t=f}}function y(a,b,c){for(var d=a.o.length,f=0;f<d&&a.o[f].c(b,c);++f);}
function z(a){for(var b=a.length,c=[],d=0,f=0;f<b;++f){var e=a.charCodeAt(f);if(0!=d){if(56320<=e&&57344>e)e=65536|d-55296<<10|e-56320;else break;d=0}if(128>e)c.push(e);else if(55296<=e&&56320>e)d=e;else{var h=128|e&63,e=e>>6;if(32>e)c.push(192|e,h);else{var g=128|e&63,e=e>>6;if(16>e)c.push(224|e,g,h);else{var k=128|e&63,e=e>>6;if(8>e)c.push(240|e,k,g,h);else break}}}}this.a=c;this.r=-1;this.F=this.a.length-1}function A(a){return a.r>=a.F?0:a.a[++a.r]}function B(a,b){this.a=a;this.f=b}
B.prototype.g=function(){return-1};B.prototype.q=function(){return[]};function C(a,b){B.call(this,a,b);this.j=[]}C.prototype=Object.create(B.prototype);C.prototype.g=function(a){var b=this.f,c=this.a[b],d=(c<<8|this.a[++b])&8191;if(c&64)for(var f=0;0!=(f=this.a[++b]);)if(A(a)!=f)return-1;if(0!=A(a))return-1;8191!=d&&this.j.push(d);if(c&32){do d=this.a[++b],d|=this.a[++b]<<8,this.j.push(d);while(65535!=d)}return 0};C.prototype.q=function(){return this.j};function D(a,b){B.call(this,a,b)}
D.prototype=Object.create(B.prototype);D.prototype.g=function(a){var b=this.f,c=this.a[b],d=c&16?2:1,c=c&15;a=A(a);for(var f=0;f<c;++f){if(a==this.a[++b])return a=this.a[++b],1==d?b=2*c+a:(a|=this.a[++b]<<8,b=3*c+a),this.f+1+b;b+=d}return-1};function E(a,b){B.call(this,a,b)}E.prototype=Object.create(B.prototype);
E.prototype.g=function(a){var b=this.f,c=this.a[b],d=this.a[++b],f=this.a[++b];a=A(a);var e=c&1;if(0==a){if(0==e)return-1}else{a-=d;if(0>a|a>=f)return-1;a+=e}c&2?(a=b+4*a,b=m(this.a,++a)):(a=b+2*a,b=this.a,c=++a,b=b[c]|b[c+1]<<8,b+=this.f);return b};function F(a){this.a=a}F.prototype.createNode=function(a){var b=this.a[a];return 192==(b&252)?new E(this.a,a):224==(b&224)?new D(this.a,a):0==(b&128)?new C(this.a,a):null};
function G(a,b){this.a=a;this.C=b;this.b=null;this.w=new F(a);this.d=!1;this.u=[]}function q(a,b,c){b=new z(b);var d=a.b.p;do{var f=a.w.createNode(d);if(!f)break;d=f.g(b);if(0==d){if(0==c.length)a=!0;else a:{b=f.q();d=b.length;for(f=0;f<d;++f)if(0<=a.b.v[b[f]].indexOf(c)){a=!0;break a}a=!1}return a}}while(0<d);return!1}function v(a,b){if(!q(a,b,"")&&(a.d=!1,y(a.b,b,a),!a.d))return;a.u.push(b)}
G.prototype.D=function(a,b){if(!this.b&&(this.b=new x(this.a,this.C),!this.b.p)||q(this,a,""))return!0;this.d=!1;y(this.b,a,this);var c=this.d;if(!c&&b){this.u=b;for(var d=this.b,f=d.t.length,e=0;e<f&&!d.t[e].c(a,this);++e);}return c};for(var I={spell:G.prototype.D},J=["org","jsspell","SpellChecker"],K=self,L=J.length-1,M=0;M<L;++M)var N=J[M],K=K[N]?K[N]:K[N]={};K[J[L]]=G;for(var O in I)G.prototype[O]=I[O];
